### ISSUE TITLE
`./tridentctl install` fails when PodSecurityPolicy is enabled

### ISSUE THREAD

**Issue by verwilst** [NetApp/trident#224]
During install:

```
# kubectl get pods -n trident
NAME                      READY   STATUS                       RESTARTS   AGE
trident-58d9bd44c-wbhdn   0/2     CreateContainerConfigError   0          96s
trident-installer         1/1     Running                      0          87s
```
```
Error: container has runAsNonRoot and image will run as root
```

I've generated the custom yaml with `./tridentctl install -n trident --generate-custom-yaml`, and edited **setup/trident-deployment.yaml** to include

```
spec:
  template:
    spec:
      securityContext:
        runAsUser: 65534
        fsGroup: 65534
```

and ran the installer with `./tridentctl install -n trident --use-custom-yaml` which resulted in:

```
# kubectl get pods -n trident
NAME                      READY   STATUS    RESTARTS   AGE
trident-78976d5d7-2lg25   2/2     Running   0          46m
```

I can confirm creating, mounting and resizing volumes work fine afterwards.

**Comment by verwilst** [comment]
FYI another way is to update the Dockerfile used to create the container to include

```
USER 65534
```

**Comment by si-heger** [comment]
I had a customer asking me if we have a general best-practice when it comes to PodSecurityPolicies? Do we support running trident as non-root or do we really require a root user?

**Comment by korenaren** [comment]
Fixed in 19.10: https://github.com/NetApp/trident/releases/tag/v19.10.0

**Comment by powo** [comment]
Still having this issue with both 18.10 and 19.10 when running on Openshift/OKD 3.11

Also the above mentioned securityContext doesn't fix it.

I couldn't find any commits/changes here, about what has been changed in 19.10 to address this
